###
###    DataBase Connection Pool Properties
###    Last Modified : Fri Dec 31 14:28:10 KST 2004
###

#oracle.vendor=oracle
#oracle.serverAddress=127.0.0.1
#oracle.portNo=1521
#oracle.sid=xe
#oracle.user=scott
#oracle.password=tiger
#oracle.maxconns=20
#oracle.initconns=5
#oracle.timeout=5
#oracle.doConnectionCheck=true
#oracle.testQueryString=select 1 from dual

###    End.
