###
###    Configuraion of HTML5 Manager
###    Last Modified : Tue Mar 30 10:26:02 KST 2021
###

#sch1.html5manager_ip=127.0.0.1
#sch1.html5manager_port=9521
#sch1.active=true
#sch1.ssl=false
#sch1.serverURL=


###    End.
