###
###    Configuraion of QRCode Manager
###    Last Modified : Wed Mar 27 09:51:06 KST 2024
###

USE_QRCODE=false
ORIGINAL_FILE_PATH=
#COMPANY_ID=
#SIGN_PRIVATE_KEY=
#PRIVATE_KEY=
#PUBLIC_KEY=
COMPANY_NAME=
SERVER_URL=

###    End.
