#-------------------------------------------
# Main configuration of ozservice
#-------------------------------------------

#enable_ozserver=true/false [ default : true ]
#enable_webservice=true/false [ default : true ]
#enable_webconsole=true/false [ default : false ]
#dataservice_defaulttype=true/false [ default : true ]
#
