###
###    Repository Properties
###    Last Modified : 2016.11.23
###

#Repository DB properties (when REPOSITORY_TYPE is RDB or HYBRID)
#RDB, HYBRID, BUILTIN, USER

#DB Alias in /conf/db.properties to use repository
#note: ignored if REPOSITORY_TYPE is BUILTIN

#REPOSITORY_TYPE=RDB
#REPOSITORY_TYPE=HYBRID
#REPOSITORY_DB_ALIAS=
#REPOSITORY_DB_OWNER=
#REPOSITORY_FILE_PATH=%OZ_HOME%/repository_hybrid_rdb_files/
#REPOSITORY_HYBRID_FILE_PATH=%OZ_HOME%/repository_hybrid_files/

#REPOSITORY_TYPE=BUILTIN
REPOSITORY_TYPE=NONE
REPOSITORY_FILE_PATH=%OZ_HOME%/repository_files/
REPOSITORY_DISTRIBUTE_PATH=

REPOSITORY_STORAGE_TYPE=LOCAL
#WASDAV attribute key value 
#REPOSITORY_STORAGE_TYPE=WEBDAV
#REPOSITORY_STROAGE_ID=
#REPOSITORY_STROAGE_PASS=

#AWSS3 attribute key value
#REPOSITORY_STORAGE_TYPE=AWSS3
#AWSS3_REGION=
#AWSS3_ACCESSKEY=
#AWSS3_SECRETKEY==
#AWSS3_BUCKET=

REPOSITORY_QUERY_MAXBACKUPINDEX=5
REPOSITORY_QUERY_MAXFILESIZE=1MB
REPOSITORY_QUERY_IMMEDIATEFLUSH=true

#BackUp History for NONE Type 
REPOSITORY_NONE_BACKUP=false                                
REPOSITORY_NONE_BACKUP_PATH=%OZ_HOME%/repository_files_bak/
REPOSITORY_NONE_BACKUP_ITEM_COUNT=10                       
REPOSITORY_NONE_BACKUP_ITEM_VALIDDAYS=0 

#Item file save number per a directory
#Default value is 500
#The value must be lager than 0 

REPOSITORY_ITEM_NUMBER_PER_DIRECTORY=500

#History item's valid days (The history item over the value of day is deleted, when check in the item) 
#Default value is 30
#The 0 value is disable.

REPOSITORY_HISTORY_ITEM_VALID_DAYS=30

#Temp Directory
REPOSITORY_TEMP_DIRECTORY=%OZ_HOME%/temp
#DELETE_TEMP_DIRECTORY=true

#Get Repository Items (Get Method)
REPOSITORY_ACCESS_BY_HTTP_GET=false
REPOSITORY_HTTP_GET_CHECK_SESSION=false

#Set server guest access
REPOSITORY_RDB_BUILTIN_GUEST_ACCESS=true

#Set item and category access permissions
#Default value is true
#If set to true, the authorized user can set the item and category access permission to all users
REPOSITORY_ITEM_CATEGORY_ACCESS_PERMISSIONS=true

#Set external login active
OZ_EXTERNAL_LOGIN.Active=false
OZ_EXTERNAL_LOGIN.Class=