#
# use user security logic apply
#

UseUserSecurityLogicVer30=false

#
# default USL(Server&Client) class name (with package name)
#


OZDefault_SERVER=oz.usl.OZUSLServerSession
OZDefault_CLIENT=oz.usl.OZUSLClientSession

#OZDefault_SERVER=oz.usl.OZUSLServerDES128
#OZDefault_CLIENT=oz.usl.OZUSLClientDES128

#OZDefault_SERVER=oz.usl.OZUSLServerAES256
#OZDefault_CLIENT=oz.usl.OZUSLClientAES256
